### PR TITLE
add uninstall target to build system

### PR DESCRIPTION
**Pull request by acxz**
Should tackle #103 

Requesting to squash and merge

### CODE REVIEW

**Comment by markusgft** [comment]
That is a nice feature, thank you @acxz .
I guess it would make sense to add the uninstallation step to the CI pipeline (see .github folder), in order to test it.
Would you be interested in adding the uninstall step there? I

**Review by markusgft — APPROVED** [review]

**Review by markusgft — CHANGES_REQUESTED** [review]
I just realize, that we will have to uninstall the unit tests as well, since they are separately installed in all test CMakeLists.txt

**Comment by acxz** [comment]
It should be fine no? The installed files associated with the tests are listed under the `install_manifest.txt` so they will be uninstalled along with the rest of the files.

**Comment by markusgft** [comment]
> 
> 
> It should be fine no? The installed files associated with the tests are listed under the `install_manifest.txt` so they will be uninstalled along with the rest of the files.

Okay, thanks for clarifying. Then it is fine of course!

**Review by markusgft — APPROVED** [review]

**Pull request merged**
