### PR TITLE
use blasfeo/hpipm targets

### LINKED ISSUE #148: Cannot find blasfeo headers because CMake does not include them despite finding blasfeo
Dear developers,
I downloaded hpipm and blasfeo from their respective git repositories here on Github and built/installed them on my machine. When compiling the Control Toolbox with the optimal control addon, I encounter the problem that blasfeo_target.h cannot be found. **The problem could be solved** when changing line 66 in ct_optcon/CMakeLists.txt from:

`list(APPEND HPIPM_LIBS ${hpipm_LIBRARIES} ${blasfeo_LIBRARIES})`
to:
`list(APPEND HPIPM_LIBS hpipm blasfeo)`

CMake does not require you to add `${<name>_LIBRARIES}` and `${<name>_INCLUDE_DIRS}` to link against dependencies or include their headers. Just link the target created by `find_package()`, this will also include all headers. I believe that this way is less error prone and should be preferred.

Edit: I did not encounter any problem with this, but int ct_core/CMakeLists.txt you added the Python libraries with `${Python_LIBRARIES}` and `${PYTHON_INCLUDE_DIRS}`. You can simply link against `Python::Python` according to [this page in the CMake manual](https://cmake.org/cmake/help/git-stage/module/FindPython.html).

### PR DESCRIPTION
**Pull request by acxz**
Addresses and resolves #148

### CODE REVIEW

**Review by markusgft — APPROVED** [review]
Hi @acxz, thanks for addressing and fixing this.
Just a sidenote -- it seems that we can also clean up the corresponding FindXXX.cmake files, see e.g. [here for blasefeo](https://github.com/ethz-adrl/control-toolbox/blob/3f801f938aeb26711c576160ad8219bf51c98374/ct_optcon/cmake/Findblasfeo.cmake#L33), and there would be a similar file for hpipm...

**Comment by acxz** [comment]
ah I can take care of that later today

**Comment by acxz** [comment]
Would it be okay if we just remove the FindXXX.cmake files? Since essentially we are just calling `find_package(XXX)` anyway. If people want to use a specific directory install of blasfeo/hpipm then they can set `-DCMAKE_PREFIX_PATH` or prepend the values to their `LD_LIBRARY_PATH` and `CPATH`/`C{PLUS}_INCLUDE_PATH`.

**Review by markusgft — CHANGES_REQUESTED** [review]
Hi, this does not seem to work out of the box on my machine, with deleted Findblasfeo.cmake and Findhpipm.cmake.

**Comment by acxz** [comment]
Can I ask where you have installed `blasfeo` and `hpipm`? I assume they were under `/opt/...`.
Did the build still not work with `-DCMAKE_PREFIX_PATH`?

Can you try running `./build_ct.sh -DCMAKE_PREFIX_PATH="/opt/blasfeo;/opt/hpipm"`?

**Comment by markusgft** [comment]
I am doubting that it is a good idea to force the user to include the path to hpipm and blasfeo using -DCMAKE_PREFIX_PATH. In fact, I would prefer if we keep the FindXXX.cmake scripts, since they make integrating hpipm a bit more user-friendly. But, I think we could get rid of the hpipm_LIBRARIES and blasfeo_LIBRARIES tags.

**Comment by acxz** [comment]
kk got it, I'll revert the deletion.

**Review by markusgft — APPROVED** [review]

**Review by markusgft — APPROVED** [review]

**Pull request merged**
